### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by yang-wei** [yang-wei/rd3#10]
@jonase

The `CONTRIBUTING.md` is kind of outdated and I prefer [airbnb eslint config](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb). 

Currently we are using gulp for build tools but if using npm scripts can achieve the same thing then we can avoid gulp.

I do not hold particular style regarding to linting. Feel free to discuss anything here =)

**Comment by jonase** [comment]
@yang-wei I prefer airbnb config as well. I'll configure running eslint as an npm script and open a pr.
