### ISSUE TITLE
Transition to `import PropTypes from 'prop-types'` from `React.PropTypes`

### ISSUE THREAD

**Issue by ghost** [yang-wei/rd3#106]
React v16 is deprecating using `React.PropTypes`.

I'd make a PR, but I feel like it might be easier for you to just do it so I don't have to point a repo at my github fork for a little while and then move it back when I notice it's been merged.

Cheers!

**Comment by yang-wei** [comment]
@flodonsky I dont have time to do this but I will merge your pr if you send me one

**Comment by ghost** [comment]
@yang-wei I was afraid you were going to say that haha I feel like everyone would love me for it so I may just do it, but really who has the time!?

**Comment by ghost** [comment]
Oh no, this was also of the React.createClass era of ReactJS as well, this would be quite the undertaking. I'll table this until it becomes a need to do. I've been looking at google charts and may just write a simple wrapper for that at this point

**Comment by brantphoto** [comment]
I've got a working fix for this that I plan to open a pull request perhaps today. @yang-wei the basics of my changes will be switch out the 'prop-types' and swapping react.createClass for the package 'create-react-class'. This is as low impact as it gets in terms of coding I will certainly need your review that I didn't miss anything. Thanks.

**Comment by brantphoto** [comment]
PR is in yang-wei/rd3/pull/108
