### ISSUE TITLE
Tooltips should use position: absolute

### ISSUE THREAD

**Issue by jscheid** [yang-wei/rd3#12]
There are two issues with using `position: fixed` for tooltips.
1. It means the tooltip isn't affected by scrolling while the chart is, so the two will get out of sync when the user scrolls the viewport after the tooltip was placed.
2. [`position: fixed` is not necessarily relative to the viewport](https://bugs.chromium.org/p/chromium/issues/detail?id=20574).

One solution to both issues would be to calculate the offset between the hotspot's and the chart's bounding client rects and then use `position: absolute` to place the tooltip relative to the chart.

**Comment by yang-wei** [comment]
Do you mind to send us a pr ? Would be happy to guide.
