### ISSUE TITLE
Unable to put animation on donout (Pie chart)  chart and how to put a svg image in donut chart ?

### ISSUE THREAD

**Issue by shashank734** [yang-wei/rd3#34]
Hey Thanks for the Library, I have some questions How i can set animation in donuts (like tween arcs) and i want to put a svg image in donut. how i can do this ?

i wanna create something like this.

<img width="119" alt="screen shot 2016-05-24 at 5 13 39 pm" src="https://cloud.githubusercontent.com/assets/6039149/15502645/f5fa8d14-21d2-11e6-9fe6-306edeffb61f.png">

**Comment by yang-wei** [comment]
i would just say its possible if you use the api, especially for the animation you want to achieve.

If you see how pie chart is created then you might got an idea on how to put another svg image inside.

**Comment by shashank734** [comment]
Hey can you little guide how i can put animation and svg ?

can i achieve this using API ?? or i have to modify your component ? One more thing any idea how i can make this like this ? That will be great if you can provide little guidance i m new to D3.
