### ISSUE TITLE
Group Bar Chart

### ISSUE THREAD

**Issue by hnandarusdy** [yang-wei/rd3#40]
Hi, is there a way to put have a group bar chart? such as 
![image](https://cloud.githubusercontent.com/assets/14065403/16108101/575904be-33e4-11e6-8578-fd17d1f4c70c.png)

Before that, I'd really say thank you for you hard work. This is really easy to use.

**Comment by yang-wei** [comment]
Nope. I know that this is also one of the popular usage of bar chart.

If you're willing to contribute I am happy to guide =)

**Comment by brookiel** [comment]
Pull #68 should fix this.
