### ISSUE TITLE
Installing rd3 doesn't install d3?

### ISSUE THREAD

**Issue by arasmussen** [yang-wei/rd3#44]
``` javascript
$ npm install --save rd3
├── UNMET PEER DEPENDENCY d3@^3.5.0
```

And then my webpack build failed.

After running npm `install --save d3` it worked as expected.

**Comment by arasmussen** [comment]
I would expect installing `rd3` to install `d3`, or the instructions for `rd3` to be modified to mention that `d3` must be installed as well.

**Comment by yang-wei** [comment]
yup ! 

https://github.com/yang-wei/rd3/blob/master/package.json#L60

basically it also doesn't install react and react-dom

Mind to submit a pr?

**Comment by arasmussen** [comment]
@yang-wei What's the fix? To remove `peerDependencies` from `package.json`? If so I'd be happy to.

**Comment by yang-wei** [comment]
no...

just add some note in README.md
