### ISSUE TITLE
xAxisTickCount not working for LineChart

### ISSUE THREAD

**Issue by ragnika** [yang-wei/rd3#46]
xAxisTickCount props is not included in the XAxis in LineChart.

It's a minor bug and I've made a pull request for it.

Anything else I should add to LineChart while I'm at it?

PS: first time contributing to OSS, not sure how to refer to the pull request in this issue.
EDIT: Nvm. just figured it out :)

**Comment by yang-wei** [comment]
no problem. THanks for the pr. Will included it in next minor release.
