### ISSUE TITLE
yAxis is not rendered

### ISSUE THREAD

**Issue by involve-it** [yang-wei/rd3#48]
There is a bug, that can be seen even on the LineChart example: https://jsfiddle.net/YangWei/9g7zbk0h/?utm_source=website&utm_medium=embed&utm_campaign=9g7zbk0h

YAxis is not rendered. To be precise, it's path's d attribute is set incorrectly. I was able to fix it locally by changing 
d = 'M' + sign \* props.outerTickSize + ',' + range[0] + 'H0V' + range[0] + 'H' + sign \* props.outerTickSize;
to
d = 'M' + sign \* props.outerTickSize + ',' + range[0] + 'H0V' + range[1] + 'H' + sign \* props.outerTickSize;
[code](https://github.com/yang-wei/rd3/blob/master/src/common/axes/AxisLine.jsx#L52)

Can somebody fix this please, if this is really a bug?
*Note: my npm code seems little different, so I don't want to mess up with an untested pull request.

**Comment by yang-wei** [comment]
dang ! You just fixed a very important bug !

Will merge it immediately if you are up to it

**Comment by involve-it** [comment]
Sounds great! By the way, very good library, thank you!
Do you want me to fork-make PR or you'll make change yourself?

**Comment by yang-wei** [comment]
Just send me a pr if you are free to do it. 

I want to make sure everyone can contribute =)

**Comment by involve-it** [comment]
Fair enough!

Here you go: https://github.com/yang-wei/rd3/pull/50

**Comment by yang-wei** [comment]
Here it's !
https://www.npmjs.com/package/rd3
