### ISSUE TITLE
Legend.js Uncaught TypeError: Cannot read property 'category20c' of undefined

### ISSUE THREAD

**Issue by dmk23** [yang-wei/rd3#51]
I'm prototyping addition of rd3 to my existing React app (ES6, webpack, d3 v3.5.17, rd3 v0.6.5)

I grabbed exact example code from https://yang-wei.github.io/rd3/docs/new/charts/lineChart.html and copied the `<LineChart ... />` into an existing modal dialog.

Opening the page resulted in the above error in the console, traced to here:

```
  getDefaultProps: function getDefaultProps() {
    return {
      className: 'rd3-legend',
      colors: d3.scale.category20c(),
      colorAccessor: function colorAccessor(d, idx) {
        return idx;
      },
      itemClassName: 'rd3-legend-item',
      text: '#000'
    };
  },
```

Any ideas on what is going wrong here? I'm a complete n00b to D3, so not sure where to look

**Comment by dmk23** [comment]
Quick update - the problem went away when I swapped out `rd3` for basic `react-d3`. I also checked the runtime and looks like I'm running v4.1.0 of D3 even though `npm list` claims I have 3.5.17

**Comment by yang-wei** [comment]
> ES6, webpack, d3 v3.5.17, rd3 v0.6.5

Your version looks good to me. This is what I use in development too.

> Opening the page resulted in the above error in the console, traced to here:

I think you forgot to paste the error?

**Comment by dmk23** [comment]
The error name is in the title... The pasted code is where the debugger pointed it to...

**Comment by ebertmi** [comment]
This is caused by D3 >4.0 
See https://github.com/d3/d3/blob/master/CHANGES.md#ordinal-scales

**Comment by dmk23** [comment]
So is `rd3` going to get upgraded too?

I thought it is supposed to be an improved fork of the regular `react-d3`

**Comment by dmk23** [comment]
I re-did the test while enforcing D3 v3.5.17 and now rd3 worked too

There is a different problem though. When a LineChart is open within a `<Modal>` from `react-bootstrap`, the tooltip position is way off to right. Perhaps there needs to be some adjustment as to how their position is calculated (or it should be somehow configurable)

**Comment by yang-wei** [comment]
> There is a different problem though. When a LineChart is open within a <Modal> from react-bootstrap, the tooltip position is way off to right. Perhaps there needs to be some adjustment as to how their position is calculated (or it should be somehow configurable

Let's move this to a new issue
Tooltip will be made totally configurable in the next major release
