### ISSUE TITLE
Support Logarithmic scale of axes.

### ISSUE THREAD

**Issue by considerate** [yang-wei/rd3#53]
There is a previous commit 1e620263df9a5155fd1f6f1dcd40cc8c9259d0cc implementing custom
xScale and yScale for LineChart but this was reverted b39a48a1897061a90d2f5f10f63ec4984c198cfb just a couple of days later. Why is this?

I ask because I would like to support a logarithmic scaling for the y-axis instead of the default linear scaling.

**Comment by yang-wei** [comment]
I can remember why this is reverted but I will merge this if you submit a pr

**Comment by yang-wei** [comment]
please reopen this for discussion if you are interested =)
