### ISSUE TITLE
Graph point dots not the same color as given in 'colors' function

### ISSUE THREAD

**Issue by UyQTran** [yang-wei/rd3#56]
<img src="https://i.gyazo.com/791a47b068c9772ce1e32ee37101f2ce.png">

The dots on my graph isn't the same color as the color given in the 'colors' function in the LineChart component. They seem to initially be random colors then red if I hover over them.

**Comment by yang-wei** [comment]
can you submit a fiddle ?
will be helpful to look through the code

**Comment by yang-wei** [comment]
This might be the wrong usage of color accessor.
Please refer to doc or give me more information for help

**Comment by machard** [comment]
This actually happens when the graph is live updated
this line in DataSeries fixes the problem:
```
return React.createElement(VoronoiCircleContainer, {
        key: vnode.point.seriesIndex + '.' + idx, // <= this line
```
