### ISSUE TITLE
Plotting a threshold line on top of a bar chart

### ISSUE THREAD

**Issue by adrianmcli** [yang-wei/rd3#57]
Is it possible to use this library to make a chart similar to this:

![bar chart with threshold line](http://www.nature.com/nclimate/journal/v1/n8/images/nclimate1265-f1.jpg)

Additionally, can I colour the bars differently depending on whether or not they are above the threshold line?

**Comment by yang-wei** [comment]
right now it's not possible.

If you need a complex chart like this, I recommend you to build it yourself while referring to our library

**Comment by yang-wei** [comment]
btw cool graph

**Comment by adrianmcli** [comment]
Thanks! I'll try it and maybe contribute if I end up make anything useful.
