### ISSUE TITLE
XAxis stroke for BarCharts

### ISSUE THREAD

**Issue by ekmartin** [yang-wei/rd3#58]
At the moment it isn't possible (as far as I can see) to style the XAxis' `stroke` prop, as it isn't passed down.

It also looks like the bars themselves could need a slight move out from the axis as well, as it looks kind of cramped (overlapped) with strokes enabled:

![image](https://cloud.githubusercontent.com/assets/3536982/16804077/3d85e616-490a-11e6-8f6a-2ddd0b002373.png)

**Comment by yang-wei** [comment]
> At the moment it isn't possible (as far as I can see) to style the XAxis' stroke prop, as it isn't passed down.

Solved in latest release

For other bug please file another issue =)
Thanks

**Comment by ekmartin** [comment]
Nice, good job!
