### ISSUE TITLE
LineChart accessor: Cannot read property 'x' of undefined(…)

### ISSUE THREAD

**Issue by jdelafon** [yang-wei/rd3#60]
Passing `data = {lineData}`, with `lineData = []`, throws

```
TypeError: Cannot read property 'x' of undefined(…)
```

apparently because the default accessor `(d) => d.x` does not find any `d` to act upon, so it takes `undefined` instead. The following accessors solve it, but it is ugly from a user perspective:

```
xAccessor={ (d) => d ? d.x : 0 }
yAccessor={ (d) => d ? d.y : 0 }
```

Edit: similar to #43, and probably all other charts.

**Comment by yang-wei** [comment]
hmmm or we can try skipping if no data is given

**Comment by jdelafon** [comment]
Definitely, because in the case when data is not empty, the condition in the accessors  would be evaluated for every data point.

**Comment by yang-wei** [comment]
solve in latest release. Please reopen if it doesn't
