### ISSUE TITLE
LineChart domain error: <path> attribute d: Expected number, "MZ".

### ISSUE THREAD

**Issue by jdelafon** [yang-wei/rd3#61]
When the `domain` prop is given incorrectly to a `LineChart` (I just cannot figure it out), it throws

```
Error: <path> attribute d: Expected number, "MZ".
```

which is not very helpful. A better error message would be welcome.

**Comment by yang-wei** [comment]
Can  you submit a js fiddle ?

**Comment by jdelafon** [comment]
I can't reproduce, sorry :( If you can tell me roughly what it means, I can try to find it again.

**Comment by yang-wei** [comment]
In SVG `<path>` element, you can set the attribute `d` to describe the path.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d

In rd3, we provide the attribute `d` by determining your x and y value. Like here https://github.com/yang-wei/rd3/blob/master/src/areachart/DataSeries.jsx#L25

So probably there are some invalid x and y value in your data ?
