### ISSUE TITLE
BarChart: <rect> attribute width: Expected length, "NaN".

### ISSUE THREAD

**Issue by jdelafon** [yang-wei/rd3#62]
When not specifying `viewBoxObject` in a `BarChart`, it throws

```
DOMPropertyOperations.js:147Error: <rect> attribute width: Expected length, "NaN".
Error: <rect> attribute x: Expected length, "NaN".
```

Same error if the accessors are wrong and no x nor y can be accessed.

The error message should be improved.

**Comment by yang-wei** [comment]
probably related to https://github.com/yang-wei/rd3/issues/65 ?

Can you submit a jsfiddle
This shouldn't be a bug

**Comment by jdelafon** [comment]
Now I can't reproduce it either... I'll reopen with a fiddle when I encounter it again.
