### ISSUE TITLE
LineChart incorrect accessors throws: <path> attribute d: Expected number, "MNaN,NaNLNaN,NaN".

### ISSUE THREAD

**Issue by jdelafon** [yang-wei/rd3#65]
I get this when the accessors are not correct, e.g. when data.values is given as `{key: 1, val: 3}` instead of `{x: 1, y: 3}` with the default accessors:

```
LineChart: <path> attribute d: Expected number, "MNaN,NaNLNaN,NaN".
```

The error message could be improved (it took me about 15 min to figure it out).

**Comment by yang-wei** [comment]
probably duplicated of https://github.com/yang-wei/rd3/issues/61

**Comment by jdelafon** [comment]
I'd rather keep this one open to fix the error message and close #61 instead, since the former has a concrete example and the latter I couldn't reproduce.

**Comment by yang-wei** [comment]
https://github.com/yang-wei/rd3/blob/master/src/linechart/DataSeries.jsx#L25

From the default accesor in LineChart, you can see we expect your data to have `x` and `y` as the key

``` js
  getDefaultProps() {
    return {
      data: [],
      xAccessor: (d) => d.x,
      yAccessor: (d) => d.y,
      interpolationType: 'linear',
      hoverAnimation: false,
    };
  },

```

If you have different value, the you have to use your own accessor:

``` js
<LineChart
  ...
  xAccessor={d => d.key}
  yAccessor={d => d.val}
/>
```

This should solve your problem.

**Comment by jdelafon** [comment]
The problem is not the wrong accessors, but that when you use a wrong accessor, with such an error message you can search for its origin for an hour. The error message should be improved.
