### ISSUE TITLE
LineChart fails using xAccessor to parse dates

### ISSUE THREAD

**Issue by easadler** [yang-wei/rd3#66]
An error is thrown by d3 when using the date parsing xAccessor in the documentation. Here it is:

``` javascript
xAccessor={(d)=> {
              var formatter = d3.time.format("%Y-%m-%d").parse;
              return formatter(d.x);
          }} 
```

On examination, it appears thy my xAccessor is being called twice, once when calling **utils.flattenData()** in LineChart.jsx and a second time in DataSeries.jsx when defining regions. _see below_
#### DataSeries.jsx

``` javascript
    var regions = voronoi(props.value).map(function(vnode, idx) {
      var point = vnode.point.coord;

     // fails here
      if (Object.prototype.toString.call(xAccessor(point)) === '[object Date]') {
        cx = props.xScale(xAccessor(point).getTime());
      } else {
        cx = props.xScale(point.x);
      }
      // also probably fails here
      if (Object.prototype.toString.call(yAccessor(point)) === '[object Date]') {
        cy = props.yScale(yAccessor(point).getTime());
      } else {
        cy = props.yScale(yAccessor(point));
      }
```

D3 returns an error when you call xAccessor the second time because it can't use str.slice() on a datetime object. The following code fixed the problem, but I'm sure you have a more robust way of dealing with it:
#### "Fixed" DataSeries.jsx

``` javascript
 var regions = voronoi(props.value).map(function(vnode, idx) {
      var point = vnode.point.coord;

       // removed xAccessor
        cx = props.xScale(point.x);

       // removed yAccessor

        cy = props.yScale(point.y);

      circleFill = props.colors(props.colorAccessor(vnode, vnode.point.seriesIndex));

      return (
          React.createElement(VoronoiCircleContainer, {
              key: idx, 
              circleFill: circleFill, 
              vnode: vnode, 
              cx: cx, cy: cy, 
              circleRadius: props.circleRadius}
          )
      );
    }.bind(this));
```

Thanks for building an awesome library!

**Comment by yang-wei** [comment]
Thanks for the clear issue !

I am happy with your imprementation. If you send me a pr I will merge it.
Just one thing, since we are using jsx so it would be great if you can use jsx instead of `React.createElement`

**Comment by easadler** [comment]
@yang-wei I created the pr. Make sure to read the comment before you merge. I'm happy to make revisions before you merge.

**Comment by yang-wei** [comment]
hmm... can you show me what is your `data` prop ?
I might misunderstood your problem

**Comment by easadler** [comment]
My data looks like this:

**Comment by easadler** [comment]
I followed the documentation for a multiple line and for what to do with dates.

``` javascript
var lineData = [
      { 
        name: 'series1',
        values: [ { x: '2014-07-10', y: 1.2 },{ x: '2014-10-15', y: 22.1 }],
        strokeWidth: 3,
      },


xAccessor={(d)=> {
      var formatter = d3.time.format("%Y-%m-%d").parse;
      return formatter(d.x);
    }     
  }
  yAccessor={(d)=>d.y}
```

xAccessor was being called twice, which caused an error when d3 tried to parse an actual date using string methods. It works fine with the default xAccessor because it is just returning the value.  The error only happens when drawing the circles and not for the actual lines.

**Comment by yang-wei** [comment]
interesting

can you submit a jsfiddle which reproduce this error ?

**Comment by easadler** [comment]
It actually only breaks when using d3.parser(). Here is a jsfiddle: 

[https://jsfiddle.net/easadler/bh9n7n8q/](https://jsfiddle.net/easadler/bh9n7n8q/)
