### ISSUE TITLE
Allow to hide axes

### ISSUE THREAD

**Issue by jdelafon** [yang-wei/rd3#67]
I couldn't find in the documentation a way to hide the axes from a plot, like `xAxis={false}`.

**Comment by yang-wei** [comment]
nope !
We do not support this kind of feature

**Comment by yang-wei** [comment]
(Not planning to support this so far, but you can see how we implemented our chart and create your custom chart by excluding axis)

**Comment by goooseman** [comment]
just use

```
.rd3-barchart-yaxis {
  display: none;
}
```
