### ISSUE TITLE
Unexpected value NaN parsing cy attribute

### ISSUE THREAD

**Issue by terebentina** [yang-wei/rd3#73]
Using values other than `x` and `y` on a `LineChart` with `xAccessor`/`yAccessor` yields this error: `Unexpected value NaN parsing cy attribute` (also with cx).
Fiddle with the default `LineChart` example with pairs changed to a/b instead of x/y and the accessor props added: https://jsfiddle.net/terebentina/9g7zbk0h/21/

**Comment by yang-wei** [comment]
with the latest release (0.7.1), this seems working in my local development.

Please reopen this issue if it doesnt solve yours.

(Really sorry for the late reply)
