### ISSUE TITLE
How to specify line chart minimum Y value?

### ISSUE THREAD

**Issue by nurpax** [yang-wei/rd3#74]
How can I make a LineChart not use the default "auto" mode of choosing the chart min and max Y values from the input data, but rather override the minimum chart Y axis value to say zero?

Presumably this can be set somehow with some of these props: https://yang-wei.github.io/rd3/docs/new/cartesianChartPropsMixin.html - but how?  

Maybe add an example into the rd3 docs on how to do this?

**Comment by nurpax** [comment]
Found it, it _is_ in the LineChart js example but not listed in LineChart props documentation.

This seems to do the trick:

```
      domain={{y: [0,]}}
```

**Comment by yang-wei** [comment]
> Maybe add an example into the rd3 docs on how to do this?

Good one. Just send me a pull request and I will merge it

**Comment by nurpax** [comment]
I'll take a look at some point.  Also the "domain" prop should be added on the props list in the LineChart docs: https://yang-wei.github.io/rd3/docs/new/charts/lineChart.html

**Comment by nurpax** [comment]
Here's a PR for adding the domain property docs: https://github.com/yang-wei/rd3/pull/76

Not sure what's the best way for me to create jsfiddle examples in the wikibook.

**Comment by yang-wei** [comment]
merged
