### ISSUE TITLE
window.React

### ISSUE THREAD

**Issue by aferrandi** [yang-wei/rd3#89]
I'm upgrading a project to version 15.1 of react and therefore I need to use the rd3 ibrary instead of esbullington/react-d3.
The project uses requirejs to  manage the dependencies and the problem I have is that react-d3.js uses React, ReactDOM and d3 as window.React, window.ReactDOM and window.d3 instead of of calling the require function.
I understand this is a general way to use React, but in my case all the window.\* variables are undefined, and therefore rd3 does not work. 
Is there a way to let it work, possibly without changing the content of react-d3.js?

**Comment by yang-wei** [comment]
We are using peer dependencies for those library so the thing you need to do is include those script before rd3 load. 

https://github.com/yang-wei/rd3/blob/master/package.json#L60

You can see how the example in fiddle works. 

![image](https://cloud.githubusercontent.com/assets/5494874/18934211/81b079f0-8613-11e6-963d-9c99e2b052f9.png)

https://jsfiddle.net/YangWei/8t16sp9g/1/
