### ISSUE TITLE
Exporting common components.

### ISSUE THREAD

**Issue by solomon-gumball** [yang-wei/rd3#91]
It seems as though the npm build does not export the common components like axes and tooltips.  This would be a nice feature for building custom charts and would probably help others develop more visualizations!

**Comment by yang-wei** [comment]
Couldn't agree more. Mind to send me a pr ?

**Comment by solomon-gumball** [comment]
@yang-wei sure thing.  I'll have time to submit something tomorrow.

**Comment by solomon-gumball** [comment]
https://github.com/yang-wei/rd3/pull/92
