### ISSUE TITLE
svg doesn't fit its parent in the LegendChart on firefox

### ISSUE THREAD

**Issue by tonthon** [yang-wei/rd3#93]
When using a Barchart with a legend, under Firefox, the chart is clipped.

Why : 
The chart's svg tag has a height css property set to 100%.
It's parent is a div with a display property set to table-cell.
Under Firefox, to allow the svg tag to fit its parent, a height should be set on the direct parent.

Working fix : 
In https://github.com/yang-wei/rd3/blob/master/src/common/charts/LegendChart.jsx#L103
Adding
```css
height: 100%; width: 100%; 
```
on the div.

**Comment by yang-wei** [comment]
send me a pull request =)
